project_id = "your-project-id"

[functions.consultar-cpf]
verify_jwt = false

[functions.consultar-segmento]
verify_jwt = false

[functions.enviar-otp]
verify_jwt = false

[functions.ip-info]
verify_jwt = false

[functions.enviar-sms]
verify_jwt = false

[functions.verificar-turnstile]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false
